---
- set_fact:
    FAST: "--end-to-end --sensitive"
    SLOW: "--local --sensitive-local"
    GENOMEINDEX: "{{ pipeman_resources_dir }}/{{ genomeindex }}"

- name: Create bowtie2.sh script
  template: src="bowtie2.sh.j2" dest="{{ projects_dir }}/{{ tmp_dir }}/bowtie2.sh"

- name: Run bowtie2.sh script in docker
  dockercmd:
    command: /bin/bash {{ pipeman_projects_dir }}/{{ tmp_dir }}/bowtie2.sh
    image: compbio/ngseasy-bowtie2:1.0-r001
    volumes:
    - "{{ projects_dir }}:{{ pipeman_projects_dir }}"
    rm: yes
    creates:
    - "{{ projects_dir }}/{{ dupemark_bam }}"
    - "{{ projects_dir }}/{{ dupemark_flagstat }}"
    - "{{ projects_dir }}/{{ dupemark_bed }}"
  register: bowtie2_output

- debug: var=bowtie2_output.stdout_lines