---
- name: get the current time for a timestamp
  command: date +%Y%m%d%H%M%S
  register: timestamp

- debug: var=timestamp

- set_fact:
    sample_dir: "{{ curr_sample.project_id }}/{{ curr_sample.sample_id }}"
    run_date: "{{ timestamp.stdout }}"

- set_fact:
    tmp_dir: "{{ sample_dir }}/tmp"
    fastq_dir: "{{ sample_dir }}/fastq"
    alignments_dir: "{{ sample_dir }}/alignments"
    reports_dir: "{{ sample_dir }}/reports"
    vcf_dir: "{{ sample_dir }}/vcf"

- set_fact:
    fq1: "{{ fastq_dir }}/{{ curr_sample.fastq1 }}"
    fq2: "{{ fastq_dir }}/{{ curr_sample.fastq2 }}"

- set_fact:
    trim_prefix: "{{ curr_sample.sample_id }}.{{ curr_sample.ngs_type }}.{{ curr_sample.dna_prep_library_id }}.{{ curr_sample.trim }}"
    bam_prefix: "{{ curr_sample.sample_id }}.{{ curr_sample.ngs_type }}.{{ curr_sample.dna_prep_library_id }}.{{ curr_sample.ngs_platform }}.{{ curr_sample.trim }}.{{ curr_sample.aligner }}.{{ curr_sample.genomebuild }}"

- set_fact:
    paired_fq1: "{{ fastq_dir }}/{{ trim_prefix }}_1_filtered.fastq.gz"
    paired_fq2: "{{ fastq_dir }}/{{ trim_prefix }}_2_filtered.fastq.gz"
    unpaired_fq1: "{{ fastq_dir }}/{{ trim_prefix }}_1_unpaired.fastq.gz"
    unpaired_fq2: "{{ fastq_dir }}/{{ trim_prefix }}_2_unpaired.fastq.gz"

    dupemark_bam: "{{ alignments_dir }}/{{ bam_prefix }}.dupemk.bam"
    dupemark_flagstat: "{{ reports_dir }}/{{ bam_prefix }}.dupemk.bam.flagstat"
    dupemark_bed: "{{ reports_dir }}/{{ bam_prefix }}.dupemk.bed"

    dupemark_realn_bam: "{{ alignments_dir }}/{{ bam_prefix }}.dupemk.{{ curr_sample.realn }}.bam"
    dupemark_realn_flagstat: "{{ reports_dir }}/{{ bam_prefix }}.dupemk.{{ curr_sample.realn }}.bam.flagstat"
    dupemark_realn_bed: "{{ reports_dir }}/{{ bam_prefix }}.dupemk.{{ curr_sample.realn }}.bed"

- set_fact:
    bsqr_bam_in: "{{ dupemark_bam }}"
    bsqr_bam_out: "{{ alignments_dir }}/{{ bam_prefix }}.dupemk.{{ curr_sample.bsqr }}.bam"
    is_bam_tool: "{{ curr_sample.realn == 'bam-realn' and curr_sample.bsqr == 'bam-bsqr' }}"
    is_gatk_tool: "{{ curr_sample.realn == 'gatk-realn' and curr_sample.bsqr == 'gatk-bsqr' }}"

- set_fact:
    bsqr_bam_in: "{{ dupemark_realn_bam }}"
    bsqr_bam_out: "{{ alignments_dir }}/{{ bam_prefix }}.dupemk.{{ curr_sample.realn }}.{{ curr_sample.bsqr }}.bam"
  when: is_bam_tool or is_gatk_tool

- include: genome_build.yml