---
- set_fact:
     project_dir: "{{ projects_dir }}/{{ sample.project_id }}"
     sample_dir: "{{ project_dir }}/{{ sample.sample_id }}"

- name: create project dir
  file: path="{{ project_dir }}" state=directory

- name: create sample dir
  file: path="{{ sample_dir }}" state=directory

- name: create fastq dir
  file: path="{{ sample_dir }}/fastq" state=directory

- name: create tmp dir
  file: path="{{ sample_dir }}/tmp" state=directory

- name: check if fastq1 file exists
  stat: path="{{ raw_fastq_dir }}/{{ sample.fastq1 }}"
  register: fastq1_stat

- name: move fastq1 file if it is exists
  command: mv {{ raw_fastq_dir }}/{{ sample.fastq1 }} {{ sample_dir }}/{{ fastq }}/{{ sample.fastq1 }}
  when: fastq1_stat.stat.exists

- name: check if fastq2 file exists
  stat: path="{{ raw_fastq_dir }}/{{ sample.fastq2 }}"
  register: fastq2_stat

- name: move fastq2 file if it is exists
  command: mv {{ raw_fastq_dir }}/{{ sample.fastq2 }} {{ sample_dir }}/{{ fastq }}/{{ sample.fastq2 }}
  when: fastq1_stat.stat.exists