---
- set_fact:
    sample_dir: "{{ sample.project_id }}/{{ sample.sample_id }}"

- set_fact:
    pipeman_sample_dir: "{{ pipeman_projects_dir }}/{{ sample_dir }}"

- set_fact:
    fq1: "{{ pipeman_sample_dir }}/fastq/{{ sample.fastq1 }}"
    fq2: "{{ pipeman_sample_dir }}/fastq/{{ sample.fastq2 }}"
    fq1_html: "{{ sample.fq1 | regexp_replace('?fastq?gz$', '_fastqc.html') }}"
    fq2_html: "{{ sample.fq2 | regexp_replace('?fastq?gz$', '_fastqc.html') }}"
    tmp_dir: "{{ pipeman_sample_dir }}/tmp"
    fastq_dir: "{{ pipeman_sample_dir }}/fastq"

- name: Create fastqc script
  template: src="fastqc.sh.j2" dest="{{ projects_dir }}/{{ sample_dir }}/tmp/fastqc.sh"
  when: sample.fastqc == "qc-fastqc"

- name: Run fastqc script
  dockercmd:
    command: /bin/bash {{ pipeman_sample_dir }}/tmp/fastqc.sh
    image: compbio/ngseasy-fastqc:1.0-r001
    volumes:
    - "{{ projects_dir }}:{{ pipeman_projects_dir }}"
    rm: yes
    creates:
    - "{{ projects_dir }}/{{ sample_dir }}/fastq/{{ fq1_html }}"
    - "{{ projects_dir }}/{{ sample_dir }}/fastq/{{ fq2_html }}"
  register: docker_output
  when: sample.fastqc == "qc-fastqc"

- debug: var=docker_output.stdout
  when: docker_output is defined

- debug: var=docker_output.stdout_lines
  when: docker_output is defined