---
- name: Create UnifiedGenotyper.sh script
  template: src="UnifiedGenotyper.sh.j2" dest="{{ projects_dir }}/{{ tmp_dir }}/UnifiedGenotyper.sh"

- name: Run UnifiedGenotyper.sh script in docker
  dockercmd:
    command: /bin/bash {{ pipeman_projects_dir }}/{{ tmp_dir }}/UnifiedGenotyper.sh
    image: compbio/ngseasy-gatk:1.0-r001
    volumes:
    - "{{ projects_dir }}:{{ pipeman_projects_dir }}"
    rm: yes
    creates:
    - "{{ projects_dir }}/{{ raw_vcf }}"
    - "{{ projects_dir }}/{{ raw_vcf_gz }}"
    - "{{ projects_dir }}/{{ vcf_gz }}"
  register: vc_output

- debug: var=vc_output.stdout_lines