---
- name: Create bam-realn.sh script
  template: src="bam-realn.sh.j2" dest="{{ projects_dir }}/{{ tmp_dir }}/bam-realn.sh"

- name: Run bam-realn.sh script in docker
  dockercmd:
    command: /bin/bash {{ pipeman_projects_dir }}/{{ tmp_dir }}/bam-realn.sh
    image: compbio/ngseasy-glia:1.0-r001
    volumes:
    - "{{ projects_dir }}:{{ pipeman_projects_dir }}"
    rm: yes
    creates:
    - "{{ projects_dir }}/{{ dupemark_realn_bam }}"
    - "{{ projects_dir }}/{{ dupemark_realn_flagstat }}"
    - "{{ projects_dir }}/{{ dupemark_realn_bed }}"
  register: realn_output

- debug: var=realn_output.stdout_lines
